# Generated by Django 3.0.6 on 2020-06-01 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20200601_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 17, 8, 25, tzinfo=utc)),
        ),
    ]
