# Generated by Django 3.0.6 on 2020-05-31 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20200530_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 15, 27, 58, tzinfo=utc)),
        ),
    ]
