# Generated by Django 3.0.6 on 2020-06-01 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20200601_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 19, 12, 1, 770755, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 12, 1, tzinfo=utc)),
        ),
    ]
