# Generated by Django 3.0.6 on 2020-05-31 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20200531_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 21, 37, 50, tzinfo=utc)),
        ),
    ]
