# Generated by Django 3.0.6 on 2020-06-01 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20200601_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 24, 19, tzinfo=utc)),
        ),
    ]
