# Generated by Django 3.0.6 on 2020-06-01 23:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_auto_20200602_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='tags',
        ),
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 23, 18, 55, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ImageTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('confidence', models.FloatField(max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_tags', to='lots.Lot')),
            ],
        ),
    ]
