# Generated by Django 3.0.6 on 2020-06-02 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_auto_20200602_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 20, 22, 18, tzinfo=utc)),
        ),
    ]
