# Generated by Django 3.0.6 on 2020-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_auto_20200602_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
