# Generated by Django 3.0.6 on 2020-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'id']},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='users/base_icon.jpg', upload_to='media'),
        ),
    ]
