# Generated by Django 3.0.6 on 2020-05-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200527_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='users/base_icon.jpg', upload_to='media'),
        ),
    ]
